# Generated by Django 5.0.4 on 2024-04-22 09:30

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-pic.jpg', storage=storages.backends.s3.S3Storage(), upload_to='profile_pics/'),
        ),
    ]
