# Generated by Django 5.0.4 on 2024-04-25 14:55

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pics/default-profile-pic.jpg', storage=storages.backends.s3.S3Storage(), upload_to='media/profile_pics/'),
        ),
    ]
