# Generated by Django 5.0.4 on 2024-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0004_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
