# Generated by Django 5.0.4 on 2024-04-28 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0005_video_user_disliked_video_user_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_disliked',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user_liked',
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.video')),
            ],
        ),
    ]
